Repository teamterning/Terning-Server-Notification, pull requests merged in 2025-03, with the labels that each got.

#3 [🔬 setting] 프로젝트 엔티티 설계 & 연관관계 매핑
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/org/terning/TerningApplication.java
  src/main/java/org/terning/domain/Messages.java
  src/main/java/org/terning/domain/Notifications.java
  src/main/java/org/terning/domain/Scraps.java
  src/main/java/org/terning/domain/User.java
  src/main/java/org/terning/domain/common/BaseEntity.java
  src/main/java/org/terning/domain/enums/AuthType.java
  src/main/java/org/terning/domain/enums/State.java
Labels: 🐶정교🐶, 🔬 setting

#8 [🔬 setting] 패키지 구조 설계
  src/main/java/org/terning/global/config/temp
  src/main/java/org/terning/global/entity/BaseEntity.java
  src/main/java/org/terning/global/failure/ErrorResponse
  src/main/java/org/terning/global/failure/baseException
  src/main/java/org/terning/global/failure/errorCode
  src/main/java/org/terning/global/failure/globalErrorCode
  src/main/java/org/terning/global/failure/globalExceptionHandler
  src/main/java/org/terning/global/success/successCode
  src/main/java/org/terning/global/success/successResponse
  src/main/java/org/terning/message/api/temp
  src/main/java/org/terning/message/application/temp
  src/main/java/org/terning/message/common/failure/temp
  src/main/java/org/terning/message/common/success/temp
  src/main/java/org/terning/message/domain/Messages.java
  src/main/java/org/terning/message/domain/vo/temp
  src/main/java/org/terning/message/dto/temp
  src/main/java/org/terning/notification/api/temp
  src/main/java/org/terning/notification/application/temp
  src/main/java/org/terning/notification/common/failure/temp
  src/main/java/org/terning/notification/common/success/temp
  src/main/java/org/terning/notification/domain/Notifications.java
  src/main/java/org/terning/notification/domain/vo/temp
  src/main/java/org/terning/notification/dto/temp
  src/main/java/org/terning/scrap/api/temp
  src/main/java/org/terning/scrap/application/temp
  src/main/java/org/terning/scrap/common/failure/temp
  src/main/java/org/terning/scrap/common/success/temp
  src/main/java/org/terning/scrap/domain/Scraps.java
  src/main/java/org/terning/scrap/domain/vo/temp
  src/main/java/org/terning/scrap/dto/temp
  src/main/java/org/terning/user/api/temp
  src/main/java/org/terning/user/application/temp
  src/main/java/org/terning/user/common/failure/temp
  src/main/java/org/terning/user/common/success/temp
  src/main/java/org/terning/user/domain/AuthType.java
  src/main/java/org/terning/user/domain/State.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/temp
  src/main/java/org/terning/user/dto/temp
Labels: 🦊장순🦊, 🔬 setting

#10 [🎉deploy] Docker + GithubActions 를 활용한 CI/CD 자동화 구축
  .github/workflows/DEV-CI.yml
  .github/workflows/DOCKER-CD.yml
  Dockerfile
  build.gradle
Labels: 🎉deploy, 🐶정교🐶

#6 [✨ feat] 유저 이름 VO 구현
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/UserName.java
  src/main/java/org/terning/user/domain/vo/temp
  src/test/java/org/terning/user/vo/UserNameTest.java
Labels: ✨ feat, 🦊장순🦊

#14 [✨ feat] 공통 예외 처리 기능 구현
  src/main/java/org/terning/global/failure/BaseException.java
  src/main/java/org/terning/global/failure/ErrorCode.java
  src/main/java/org/terning/global/failure/ErrorResponse
  src/main/java/org/terning/global/failure/ErrorResponse.java
  src/main/java/org/terning/global/failure/GlobalErrorCode.java
  src/main/java/org/terning/global/failure/GlobalExceptionHandler.java
  src/main/java/org/terning/global/failure/baseException
  src/main/java/org/terning/global/failure/errorCode
  src/main/java/org/terning/global/failure/globalErrorCode
  src/main/java/org/terning/global/failure/globalExceptionHandler
  src/main/java/org/terning/global/success/SuccessCode.java
  src/main/java/org/terning/global/success/SuccessResponse.java
  src/main/java/org/terning/global/success/successCode
  src/main/java/org/terning/global/success/successResponse
Labels: ✨ feat, 🦊장순🦊

#16 [✨ feat] UserName에 커스텀 예외처리 적용
  src/main/java/org/terning/user/common/failure/UserErrorCode.java
  src/main/java/org/terning/user/common/failure/UserException.java
  src/main/java/org/terning/user/common/failure/temp
  src/main/java/org/terning/user/domain/vo/UserName.java
  src/test/java/org/terning/user/vo/UserNameTest.java
Labels: ✨ feat, 🦊장순🦊

#18 [✨ feat] FCM 토큰 VO 구현
  src/main/java/org/terning/user/common/failure/UserErrorCode.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/PushToken.java
  src/test/java/org/terning/user/domain/vo/PushTokenTest.java
  src/test/java/org/terning/user/domain/vo/UserNameTest.java
Labels: ✨ feat, 🦊장순🦊

#20 [✨ feat] 푸시 알람 설정 VO 구현
  src/main/java/org/terning/user/common/failure/UserErrorCode.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/PushNotificationStatus.java
  src/test/java/org/terning/user/domain/vo/PushNotificationStatusTest.java
Labels: ✨ feat, 🦊장순🦊

#23 [✨ feat] 계정 상태 VO 구현
  src/main/java/org/terning/user/common/failure/UserErrorCode.java
  src/main/java/org/terning/user/domain/State.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/AccountStatus.java
  src/test/java/org/terning/user/domain/vo/AccountStatusTest.java
Labels: ✨ feat, 🦊장순🦊

#24 [♻️ refactor] 푸시 알림 상태 enum에 외부 표현 값 추가 및 구조 개선
  src/main/java/org/terning/user/domain/vo/PushNotificationStatus.java
  src/test/java/org/terning/user/domain/vo/PushNotificationStatusTest.java
Labels: ♻️ refactor, 🦊장순🦊

#26 [✨ feat] 소셜 로그인 타입 VO 구현
  src/main/java/org/terning/user/common/failure/UserErrorCode.java
  src/main/java/org/terning/user/domain/AuthType.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/AuthType.java
  src/test/java/org/terning/user/domain/vo/AuthTypeTest.java
Labels: ✨ feat, 🦊장순🦊

#34 Feat/#25
  src/main/java/org/terning/user/common/failure/UserErrorCode.java
  src/main/java/org/terning/user/common/failure/UserException.java
  src/main/java/org/terning/user/common/failure/temp
  src/main/java/org/terning/user/domain/AuthType.java
  src/main/java/org/terning/user/domain/State.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/AccountStatus.java
  src/main/java/org/terning/user/domain/vo/AuthType.java
  src/main/java/org/terning/user/domain/vo/PushNotificationStatus.java
  src/main/java/org/terning/user/domain/vo/PushToken.java
  src/main/java/org/terning/user/domain/vo/UserName.java
  src/test/java/org/terning/user/domain/vo/AccountStatusTest.java
  src/test/java/org/terning/user/domain/vo/AuthTypeTest.java
  src/test/java/org/terning/user/domain/vo/PushNotificationStatusTest.java
  src/test/java/org/terning/user/domain/vo/PushTokenTest.java
  src/test/java/org/terning/user/domain/vo/UserNameTest.java
Labels: size/XL

#35 [♻️ refactor] 글로벌 예외 처리 개선
  src/main/java/org/terning/global/failure/GlobalExceptionHandler.java
Labels: ♻️ refactor, 🦊장순🦊, size/S

#41 [✨ feat] FCM 환경설정 및 JSON Key 관리 환경 구축
  build.gradle
  src/main/java/org/terning/TerningApplication.java
  src/main/java/org/terning/global/constant/Encoding.java
  src/main/java/org/terning/user/common/log/FcmLogMessages.java
  src/main/java/org/terning/user/config/FcmConfig.java
  src/main/java/org/terning/user/config/FcmProperties.java
Labels: ✨ feat, 🐶정교🐶, 🔬 setting, size/M

#48 [✨ feat] FCM 토큰 재발급 API 구현
  src/main/java/org/terning/TerningApplication.java
  src/main/java/org/terning/fcm/config/FcmConfig.java
  src/main/java/org/terning/global/config/temp
  src/main/java/org/terning/user/api/UserController.java
  src/main/java/org/terning/user/application/UserService.java
  src/main/java/org/terning/user/application/fcmtoken/update/FcmTokenUpdateService.java
  src/main/java/org/terning/user/application/fcmtoken/update/FcmTokenUpdateServiceImpl.java
  src/main/java/org/terning/user/common/success/UserSuccessCode.java
  src/main/java/org/terning/user/config/FcmConfig.java
  src/main/java/org/terning/user/config/FcmProperties.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/vo/FcmToken.java
  src/main/java/org/terning/user/dto/request/UpdateFcmTokenRequest.java
  src/test/java/org/terning/TerningApplicationTests.java
  src/test/java/org/terning/user/application/fcmtoken/update/FcmTokenUpdateServiceImplTest.java
Labels: ✨ feat, 🦊장순🦊, size/L
