Repository teamterning/Terning-Server-Notification, pull requests merged in 2025-04, with the labels that each got.

#51 [♻️ refactor] 메시지 포맷 로직을 내부로 이동하여 생성 책임 명확화 및 응집도 개선
  src/main/java/org/terning/message/domain/Message.java
  src/test/java/org/terning/message/domain/MessageTest.java
Labels: ♻️ refactor, 🦊장순🦊, size/M

#53 [✨ feat] 운영서버에서 스크랩 유저 조회 후 저장하는 동기화 로직 구현
  .gitignore
  build.gradle
  src/main/java/org/terning/TerningApplication.java
  src/main/java/org/terning/global/config/QuerydslConfig.java
  src/main/java/org/terning/global/config/WebClientConfig.java
  src/main/java/org/terning/infra/ops/scrap/OpsScrapUserClient.java
  src/main/java/org/terning/infra/ops/scrap/dto/response/OpsScrapUserResponse.java
  src/main/java/org/terning/infra/ops/scrap/dto/response/OpsScrapUsersResponse.java
  src/main/java/org/terning/scrap/api/ScrapController.java
  src/main/java/org/terning/scrap/api/temp
  src/main/java/org/terning/scrap/application/ScrapService.java
  src/main/java/org/terning/scrap/application/ScrapStatusSyncService.java
  src/main/java/org/terning/scrap/application/ScrapStatusSyncServiceImpl.java
  src/main/java/org/terning/scrap/application/ScrapSyncManager.java
  src/main/java/org/terning/scrap/application/temp
  src/main/java/org/terning/scrap/batch/ScrapUserSyncJobConfig.java
  src/main/java/org/terning/scrap/batch/processor/ScrapUserItemProcessor.java
  src/main/java/org/terning/scrap/batch/reader/ScrapUserItemReader.java
  src/main/java/org/terning/scrap/batch/scheduler/ScrapUserSyncJobScheduler.java
  src/main/java/org/terning/scrap/batch/step/ScrapSyncWriter.java
  src/main/java/org/terning/scrap/domain/ScrapRepository.java
  src/main/java/org/terning/scrap/domain/ScrapRepositoryCustom.java
  src/main/java/org/terning/scrap/domain/ScrapRepositoryImpl.java
  src/main/java/org/terning/user/domain/UserRepository.java
  src/main/java/org/terning/user/domain/UserRepositoryCustom.java
  src/main/java/org/terning/user/domain/UserRepositoryImpl.java
  src/test/java/org/terning/scrap/application/ScrapStatusSyncServiceImplTest.java
  src/test/java/org/terning/scrap/application/ScrapSyncManagerTest.java
  src/test/java/org/terning/scrap/batch/step/ScrapSyncWriterTest.java
  src/test/java/org/terning/scrap/domain/ScrapRepositoryTest.java
  src/test/java/org/terning/user/domain/UserRepositoryTest.java
Labels: ✨ feat, 🦊장순🦊, size/XXL

#55 [✨ feat] 메시지-유저 조합을 통해 알림 생성 및 저장 배치 구현
  src/main/java/org/terning/message/api/temp
  src/main/java/org/terning/message/application/temp
  src/main/java/org/terning/message/domain/Message.java
  src/main/java/org/terning/message/domain/enums/MessageTemplateType.java
  src/main/java/org/terning/message/domain/enums/SendSchedulePolicy.java
  src/main/java/org/terning/message/domain/vo/MessageWeeklyPolicy.java
  src/main/java/org/terning/notification/api/NotificationController.java
  src/main/java/org/terning/notification/api/temp
  src/main/java/org/terning/notification/application/NotificationService.java
  src/main/java/org/terning/notification/application/command/NotificationCommandService.java
  src/main/java/org/terning/notification/application/command/NotificationCommandServiceImpl.java
  src/main/java/org/terning/notification/application/executor/NotificationCreationExecutor.java
  src/main/java/org/terning/notification/application/executor/NotificationCreationExecutorImpl.java
  src/main/java/org/terning/notification/application/temp
  src/main/java/org/terning/notification/application/writer/NotificationWriter.java
  src/main/java/org/terning/notification/application/writer/NotificationWriterImpl.java
  src/main/java/org/terning/notification/batch/executor/NotificationCreationTasklet.java
  src/main/java/org/terning/notification/batch/schedule/NotificationScheduler.java
  src/main/java/org/terning/notification/batch/step/NotificationJobConfig.java
  src/main/java/org/terning/notification/common/failure/NotificationErrorCode.java
  src/main/java/org/terning/notification/common/failure/NotificationException.java
  src/main/java/org/terning/notification/common/failure/temp
  src/main/java/org/terning/notification/domain/Notification.java
  src/main/java/org/terning/notification/domain/Notifications.java
  src/main/java/org/terning/notification/domain/NotificationsRepository.java
  src/main/java/org/terning/notification/domain/vo/ScheduledTime.java
  src/main/java/org/terning/notification/domain/vo/SentStatus.java
  src/main/java/org/terning/notification/domain/vo/temp
  src/main/java/org/terning/notification/dto/request/NotificationCreateRequest.java
  src/main/java/org/terning/notification/dto/temp
  src/main/java/org/terning/scrap/batch/scheduler/ScrapUserSyncJobScheduler.java
  src/main/java/org/terning/scrap/common/failure/ScrapErrorCode.java
  src/main/java/org/terning/scrap/domain/ScrapRepositoryCustom.java
  src/main/java/org/terning/scrap/domain/ScrapRepositoryImpl.java
  src/main/java/org/terning/scrap/domain/Scraps.java
  src/main/java/org/terning/user/domain/User.java
  src/test/java/org/terning/message/domain/MessageTest.java
  src/test/java/org/terning/notification/application/writer/NotificationWriterImplTest.java
  src/test/java/org/terning/notification/domain/NotificationsRepositoryTest.java
  src/test/java/org/terning/scrap/domain/ScrapRepositoryTest.java
Labels: ✨ feat, 🦊장순🦊, size/XXL

#59 [✨ feat] 운영서버-알림서버 동기화 응답 반환
  src/main/java/org/terning/infra/ops/scrap/OpsScrapUserClient.java
  src/main/java/org/terning/scrap/api/ScrapController.java
  src/main/java/org/terning/scrap/application/ScrapStatusSyncServiceImpl.java
  src/main/java/org/terning/scrap/batch/ScrapUserSyncJobConfig.java
  src/main/java/org/terning/scrap/batch/processor/ScrapUserItemProcessor.java
  src/main/java/org/terning/scrap/batch/reader/ScrapUserItemReader.java
  src/main/java/org/terning/scrap/batch/step/ScrapSyncWriter.java
  src/main/java/org/terning/scrap/config/OpsScrapUserClient.java
  src/main/java/org/terning/scrap/dto/request/ScrapUserIdsRequest.java
  src/main/java/org/terning/scrap/dto/response/OpsScrapUserResponse.java
  src/main/java/org/terning/scrap/dto/response/OpsScrapUsersResponse.java
  src/main/java/org/terning/scrap/dto/temp
  src/test/java/org/terning/scrap/application/ScrapStatusSyncServiceImplTest.java
  src/test/java/org/terning/scrap/batch/step/ScrapSyncWriterTest.java
Labels: ✨ feat, 🦊장순🦊, size/L

#61 [✨ feat] 푸시 알림 발송 시 다중 스케줄 정책 적용
  src/main/java/org/terning/message/common/failure/MessageErrorCode.java
  src/main/java/org/terning/message/domain/Schedules.java
  src/main/java/org/terning/message/domain/enums/SendSchedulePolicy.java
  src/main/java/org/terning/message/domain/vo/MessageWeeklyPolicy.java
  src/main/java/org/terning/message/domain/vo/Schedule.java
  src/main/java/org/terning/notification/batch/schedule/NotificationScheduler.java
  src/main/java/org/terning/scrap/batch/scheduler/ScrapUserSyncJobScheduler.java
Labels: ✨ feat, 🦊장순🦊, size/L

#63 [✨ feat] 알림 서버에서 유저 상태 동기화 작업 및 API 구현
  src/main/java/org/terning/user/api/UserController.java
  src/main/java/org/terning/user/application/UserService.java
  src/main/java/org/terning/user/common/success/UserSuccessCode.java
  src/main/java/org/terning/user/domain/User.java
  src/main/java/org/terning/user/domain/UserRepository.java
  src/main/java/org/terning/user/domain/UserRepositoryCustom.java
  src/main/java/org/terning/user/domain/UserRepositoryImpl.java
  src/test/java/org/terning/user/domain/UserRepositoryTest.java
Labels: ✨ feat, 🐶정교🐶, size/M

#67 [✨ feat] 푸시 알림 전체 발송 관련 알림서버 API 구현
  src/main/java/org/terning/fcm/api/PushNotificationController.java
  src/main/java/org/terning/fcm/application/FcmPushSender.java
  src/main/java/org/terning/fcm/application/FcmPushSenderImpl.java
  src/main/java/org/terning/fcm/application/PushNotificationService.java
  src/main/java/org/terning/user/application/UserService.java
Labels: ✨ feat, 🐶정교🐶, size/L

#69 [🔨 Fix] 푸시알림 서버 QA를 위한 코드 수정 및 요구사항 고도화
  src/main/java/org/terning/notification/api/NotificationController.java
  src/main/java/org/terning/notification/application/writer/NotificationWriterImpl.java
  src/main/java/org/terning/notification/domain/Notification.java
  src/main/java/org/terning/scrap/domain/Scrap.java
  src/main/java/org/terning/user/api/UserController.java
  src/main/java/org/terning/user/application/UserService.java
Labels: 🐶정교🐶, 🔨 fix, size/M

#71 [♻️ refactor/#70] FCM 데이터 페이로드 형식 수정
  src/main/java/org/terning/fcm/application/FcmPushSenderImpl.java
  src/main/java/org/terning/message/domain/Message.java
  src/main/java/org/terning/message/domain/enums/ViewType.java
Labels: ♻️ refactor, 🐶정교🐶, size/S

#73 [♻️ refactor/#72] FCM 데이터 페이로드 형식 수정
  src/main/java/org/terning/fcm/application/FcmPushSenderImpl.java
  src/main/java/org/terning/message/domain/Message.java
  src/main/java/org/terning/message/domain/enums/MessageTemplateType.java
  src/main/java/org/terning/notification/application/writer/NotificationWriterImpl.java
Labels: ♻️ refactor, 🐶정교🐶, size/S

#75 [♻️ refactor] 푸시알림 imageUrl 변경
  src/main/java/org/terning/message/domain/enums/MessageTemplateType.java
Labels: ♻️ refactor, 🐶정교🐶, size/XS
